### PR TITLE
fix: s2i build as-dockerfile mode

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes
* Use `"as dockerfile"` mode of `s2i` builds:
  Rationale: `podman` < 4.0 has faulty `/commit` endpoint so `"daemon mode"` is not working

/kind bug

```release-note
fix: s2i+podman<4.0 build error "CommitFailure: invalid change "LABEL" - must be formatted as KEY VALU"
```

### CODE REVIEW

**Comment by matejvasek** [comment]
This version inspects appropriate label and sets s2i script url. This fixes the issue with openjdk builds.

**Comment by matejvasek** [comment]
@lance @lkingland @zroubalik  PTAL

**Comment by matejvasek** [comment]
Too bad this won't make it to midstream release. Maybe we could do at least upstream release?

**Review by zroubalik — APPROVED** [review]
/lgtm

/hold - merge as you like

**Comment by lkingland** [comment]
Good workaround 
/lgtm as well

**Comment by matejvasek** [comment]
To be honest I not super happy about this since this introduces unnecessary project copy but this is only way how to make this work on `podman v3.3`.

**Pull request merged**
