### PR TITLE
Update Knative to 0.25 + cherry-pick E2E refactor

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- :broom: Update Knative to 0.25 release 
- :broom: E2E test refactor

### CODE REVIEW

**Comment by lance** [comment]
@lkingland I think you'll need to consent to keep google bot happy

**Comment by lkingland** [comment]
@googlebot I consent.

**Comment by dsimansk** [comment]
@lance @lkingland nice to see green CI once a while. It seems to be ready. :)

**Review by lkingland — APPROVED** [review]
/lgtm

**Pull request merged**
