### PR TITLE
[fix] Docs typo: "Knaive" -> "Knative"

### PR DESCRIPTION
**Pull request by bbtong**
Signed-off-by: Bryan Tong <tongb@vmware.com>

# Changes

- Fix typo of "Knaive" -> "Knative>

/kind documentation

No issue exists since it's a small typo

**Release Note**
Fix typo in developer's docs

```release-note
Fix typo in documentation
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by bbtong** [comment]
Super small PR 😆

**Review by zroubalik — APPROVED** [review]
/lgtm
/approve

Thanks!

**Review by lance — COMMENTED** [review]
/lgtm

**Pull request merged**
