### PR TITLE
fix: `build` should honor registry specified in `-r`

### LINKED ISSUE #506: `func deploy` registry options from command line (`-r`) should take precedence over registry on `func.yaml`
When you build a project using a testing repository that repo get saved on func.yaml.
Then when you use deploy command the specifying a different repository, func honor (func.yaml) and does not uses the specific setting passed on command line

```
$ kn func build -r localhost:5000/test
   🙌 Function image built: localhost:5000/test/myfunc:latest
$ kn func deploy -r quay.io/jrangelramos -v
Building function image
...
Pushing function image to the registry
The push refers to repository [localhost:5000/test/myfunc] (100%)
...
```

I think a command line options should take precedence in this case.

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

# Changes

- :bug: `build` should honor registry specified in `-r`

Fixes #506

### CODE REVIEW

**Review by lance — COMMENTED** [review]
Looks good - what do you think about adding a test @zroubalik ?

**Review by lkingland — APPROVED** [review]
/lgtm

**Comment by lkingland** [comment]
Drat.  It merged the PR before I could add the /hold label to wait for an answer on the potential test requested by @lance

**Comment by zroubalik** [comment]
@lkingland I will add tests in another PR

**Pull request merged**
