### PR TITLE
Update Knative dependencies to 0.26

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- :broom: Update Knative dependencies to 0.26

/cc @lance

### CODE REVIEW

**Review by lance — COMMENTED** [review]
I'm not going to scroll through 1500 files to review, and will assume that these are all just automated deps updates. Yikes! ;-)

/lgtm

**Comment by dsimansk** [comment]
> I'm not going to scroll through 1500 files to review, and will assume that these are all just automated deps updates. Yikes! ;-)
> 
> /lgtm

Sure, it's update with magic script :)
```
./hack/update-deps.sh --upgrade --release v0.26
```

@lance I've rebased the PR, it will need another lgtm.

**Pull request merged**
