### PR TITLE
chore: use lower case *functions* in all CLI outputs

### LINKED ISSUE #1122: Help text in command prompt sometimes use functions and sometimes Functions
image

Ask for consistency in writing Functions in the help command

### PR DESCRIPTION
**Pull request by gauron99**
# Changes
CLI output visual change:  *functions instead of Functions* + minor misspells i noticed
I went to `cmd/root.go` file and followed all subcommands and changed all **strings** and **comments** that containted "function" in some way (hopefully i didnt miss anything :smile: )
- *comments*: change unless its part of a function's name (like bindFunc) or beginning of a sentence
- *strings*: change unless its the beginning of a sentence (like prints and errors or survey messages)
/kind cleanup

Fixes #1122

### CODE REVIEW

**Review by lance — COMMENTED** [review]
/lgtm ty for also applying to "Project" where needed

**Comment by gauron99** [comment]
I've noticed some more error messages (and comments) in other files, in sake of completion I'm gonna add them to this PR ( I am probably going to end up going over all the files but I thought since we are changing CLI outputs it seems cleaner to unify all of them with comments too).
@zroubalik @lance let me know if this is unnecessary or feel free to unhold I'm gonna wait for your response before pushing anything new
/hold

**Comment by lance** [comment]
@gauron99 please feel free to continue! 😉

**Review by zroubalik — APPROVED** [review]
/lgtm

Quite big PR afterall, great job :)

**Comment by lance** [comment]
@gauron99 whenever you are ready, you can go ahead and unhold

**Pull request merged**
