### PR TITLE
Update Knative dependencies to v1.7

### PR DESCRIPTION
**Pull request by dsimansk**
This PR updates Knative deps. In addition it should verify that it's possible to do it from macOS. :)

/cc @lance

# Changes

- Update Knative dependencies to v1.7
- Update `vendor/` dir

### CODE REVIEW

**Comment by salaboy** [comment]
@dsimansk there seems to be some issues with 
```
Error: vendor/knative.dev/pkg/changeset/commit.go:57:24: info.Settings undefined (type *debug.BuildInfo has no field or method Settings)

```

**Comment by matejvasek** [comment]
maybe bad go version?

**Comment by matejvasek** [comment]
@dsimansk  please rebase to fix the failing tests.

**Comment by dsimansk** [comment]
Hopefully, this PR is superseded by #1245 and without fs shenanigans.

**Comment by dsimansk** [comment]
No longer needed.
/close

**Pull request closed without merging**
