### PR TITLE
configuring pipeline to avoid changing buildpacks

### LINKED ISSUE #827: Handling source files deletion in on-cluster-builds
While doing on cluster builds for go runtime, and making use of the builder `ghcr.io/boson-project/go-function-builder:tip` compiled from: https://github.com/boson-project/packs, I noticed that the custom buildpack in this builder is attempting to remove source files so that they dont appear in the final runnable image, and this won't really cause a problem when using the pack cli or its go client to build images - the problem happens if we use this builder in on-cluster-builds, where the source code is present in a pvc backed workspace, because now the removal of source files will cause mutation of the source code, and hence the tekton tasks after the build task that are either reading or in general using the source files _will fail_, specifically the `image-digest` and `deploy` tasks.
In case of usual `pack build`, the source files are uploaded to a new container from local machine fs, and so mutations are done to the source files in that container and not the local machine. 

As far as I could understand from the buildpacks slack thread here: https://buildpacks.slack.com/archives/C94UJCNV6/p1644416841067679, there is no standardization around the source file removal aspect in a buildpack currently, some languages do it and some don't. For example, for nodejs, the paketo builder wont remove the source files, but for rust, the paketo community rust builder will do the removal, same is the case for the boson go builder rn. 

Two ways this issue can be handled:

1. configuring the builder/buildpack to avoid removing the source files, which I feel is a overhead and can have certain implications around security, size of the final runnable image etc
for boson go builder, here is a PR attempting this: https://github.com/boson-project/packs/pull/8

2. changing the tekton pipeline - to backup the source files in a different path in the workspace before running the build task, and then restoring the files back to the original path for post build tasks. 
I have created a sample pipeline for this, which is all green without accommodating the PR changes in point 1 - I am cleaning it up, and will create a PR for it soon. 

ref: https://knative.slack.com/archives/CUU6LEMRT/p1643893973744699

### PR DESCRIPTION
**Pull request by Shashankft9**
# Changes

- adds two tekton tasks: `backup-source` and `restore-source` to avoid configuring buildpack/builder to _not_ remove the source files
- using boson go builder

/kind bug

Fixes #827  #809

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
@Shashankft9 do we really need to do this? I am sorry, I haven't had a time to follow the recent stuff. But I'd be definitely more inclined towards changing the builders in case they are removing anything from the source code. Adding new tekton tasks brings a lot of additional complexity.

If these kind of chnages are necessary, then we should include them into a build task, so the source is in a correct state after running the build step.

**Comment by zroubalik** [comment]
> @zroubalik hey, regarding changing pipeline vs changing buildpacks - I have tried to capture the gist from the slack threads here: #827, wdyt about that?
> 
> And yeah, I agree, it would be better to anyway add these 2 tasks as steps in `build` task.

Thanks, I will check that issue, I missed it somehow, sorry.

**Comment by Shashankft9** [comment]
@zroubalik thoughts on this? should I try the change of putting the new 2 tasks as steps instead - if this is how we would like to proceed considering the issue mentioned above.

**Comment by Shashankft9** [comment]
@zroubalik added the build task yaml file in the pipeline resources of the kn-plugin-func repo - with 2 steps, backup and restore of source code. 
because of this, the documentation will change slightly for the apply of buildpack task, but I can take care of that in another PR, let me know.

**Comment by zroubalik** [comment]
> @zroubalik added the build task yaml file in the pipeline resources of the kn-plugin-func repo - with 2 additional steps, backup and restore of source code. because of this, the documentation will change slightly for the apply of buildpack task, but I can take care of that in another PR, let me know.

Sorry for the delay, though I'd prefer if we change the Go and Rust builders to not delete the function source code and config, so we have consistent experience with all runtimes. WDYT?

**Comment by Shashankft9** [comment]
> so we have consistent experience with all runtimes

thats actually my concern, in the slack thread of buildpacks I have linked in the original issue, i got to learn that there really is no standard in buildpacks today to handle source file deletion, so some do and some don't. So I see two choices, either to change buildpacks that do the source file deletion, maybe in future there will be more OR handle it like this. 
I do see your point though, in case if we are going to maintain buildpacks, then it makes sense to do the changes at buildpacks level, but the pipeline change still looks more simpler to me - although, I havent really worked much with CICD systems so I wouldn't know how hard it would be to do the same for systems other than tekton etc. 
and then there are security concerns like https://github.com/knative-sandbox/kn-plugin-func/issues/357 that @matejvasek briefly talked about in the slack thread.

**Comment by matejvasek** [comment]
BTW I just noticed that paketo java BP probably does delete sources.

**Comment by lance** [comment]
@Shashankft9 I am going to go ahead and close this, since I think the problem has been addressed with a less resource intensive workaround in this PR https://github.com/knative-sandbox/kn-plugin-func/pull/1070. Thanks for your contribution in any case!

**Pull request closed without merging**
