### PR TITLE
Change github.com links to the new home

### PR DESCRIPTION
**Pull request by markusthoemmes**
As the title says, pretty much a replace of `github.com/boson-project/[func|faas]` with the new coordinates.

### CODE REVIEW

**Review by lkingland — APPROVED** [review]
/lgtm

Thanks Markus

**Comment by lkingland** [comment]
(CI failure is fixed in #419)

**Comment by lance** [comment]
> (CI failure is fixed in #419)

Re-running CI jobs now that #419 has landed. Hopefully that will succeed.

**Comment by lance** [comment]
/lgtm

TY

**Pull request merged**
