### PR TITLE
chore: add release process and func_darwin_arm64 to the release artifacts

### PR DESCRIPTION
**Pull request by lance**
# Changes

- 🧹  add func_darwin_arm64 to release artifacts

The MacOS M1 binary was omitted from the release artifacts when added in https://github.com/knative-sandbox/kn-plugin-func/pull/932

ADDENDUM:

I noticed in the most recent release, that a MacOS M1 binary was not produced. This commit adds that target to `hack/release.sh`. Additionally the CHANGELOG.md files and version.txt files have been updated to accurately
reflect the current status. Finally, I've proposed a release process in the new file `docs/RELEASING.md`.

/kind chore

### CODE REVIEW

**Comment by matejvasek** [comment]
>Merging [#945](https://codecov.io/gh/knative-sandbox/kn-plugin-func/pull/945?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=knative-sandbox) (https://github.com/knative-sandbox/kn-plugin-func/commit/db65653063548abd843e06793cf9e835288e48b2) into [main](https://codecov.io/gh/knative-sandbox/kn-plugin-func/commit/739cded50f149623f281a83717c9b929105102e1?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=knative-sandbox) (https://github.com/knative-sandbox/kn-plugin-func/commit/739cded50f149623f281a83717c9b929105102e1) will increase coverage by 1.98%.

How is this increasing coverage?

**Comment by lance** [comment]
> > Merging [#945](https://codecov.io/gh/knative-sandbox/kn-plugin-func/pull/945?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=knative-sandbox) ([db65653](https://github.com/knative-sandbox/kn-plugin-func/commit/db65653063548abd843e06793cf9e835288e48b2)) into [main](https://codecov.io/gh/knative-sandbox/kn-plugin-func/commit/739cded50f149623f281a83717c9b929105102e1?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=knative-sandbox) ([739cded](https://github.com/knative-sandbox/kn-plugin-func/commit/739cded50f149623f281a83717c9b929105102e1)) will increase coverage by 1.98%.
> 
> How is this increasing coverage?

LOL I have no idea

**Comment by lance** [comment]
@matejvasek I added some verbiage around the release process as a whole and the lgtm label was removed. Could you ptal?

**Comment by matejvasek** [comment]
Please fix the `Code Style` error first.

**Review by zroubalik — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
