### PR TITLE
feat: build for Linux ARM64

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :gift: Add build for Linux/arm64

/kind enhancement

### CODE REVIEW

**Comment by csantanapr** [comment]
Thank you so much for this @matejvasek ❤️

**Review by lance — COMMENTED** [review]
@matejvasek can you add the binary to the release script here? https://github.com/knative-sandbox/kn-plugin-func/blob/cccb2833d1ad8f77cfb200ef4f43a7e4098af92d/hack/release.sh#L28 

And we should update the brew scripts in https://github.com/knative-sandbox/homebrew-kn-plugins as well.

**Comment by matejvasek** [comment]
@lance PTAL

**Review by lance — COMMENTED** [review]
/lgtm

**Pull request merged**
