### PR TITLE
chore: update manifest.yamls

### PR DESCRIPTION
**Pull request by lance**
# Changes

- :bug: In a couple of cases, the `invoke` parameter was missing. 
- :bug: There was an outdated use of a typescript buildpack in the typescript/cloudevent templates.

Signed-off-by: Lance Ball <lball@redhat.com>

/kind bug

**Release Note**

```release-note
Fixes missing `cloudevent` invocation format for Node.js, SpringBoot and Rust CloudEvent templates
```

### CODE REVIEW

**Comment by matejvasek** [comment]
@lance were are the TS changes?

**Comment by lance** [comment]
@matejvasek here: https://github.com/knative-sandbox/kn-plugin-func/pull/846/commits/462696f07a68787d9e139fca5ef73b9d7c2eec5c

**Comment by matejvasek** [comment]
>fixup: I should set VSCode to autosave on focus change

I learned obsessively press CTRL+S everywhere :smile:

**Pull request merged**
