### PR TITLE
Improvements for podman on Windows and macOS

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :bug: Fix docker socket mount for npipe on Windows.
- :bug: Fix docker socket mount for docker socket tunnelled from podman VM.
- :gift: Trust ssh connection provided by `podman` machine (so user is not unnecessarily prompted).

### CODE REVIEW

**Comment by matejvasek** [comment]
PTAL @lance @lkingland @zroubalik

**Comment by matejvasek** [comment]
@jrangelramos does the coverage-bot merge coverages from various operating systems together?

**Review by lkingland — APPROVED** [review]
/lgtm
/hold for others
especially like we can use the official Microsoft library

**Comment by matejvasek** [comment]
>especially like we can use the official Microsoft library

yeah, too bad it don't work with `wine` :disappointed: 
but I figured how to invoke test via `SSH`.

**Pull request merged**
