### PR TITLE
fixed a variable name error in docs

### PR DESCRIPTION
**Pull request by chzhyang**
# Changes
- :bug: variable `body` was misspelled to data

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
good catch!

/lgtm

**Review by lkingland — APPROVED** [review]
/lgtm
Thanks for the fix @chzhyang

**Comment by matejvasek** [comment]
@lkingland there are not changes to template in this PR it seems

**Comment by matejvasek** [comment]
@chzhyang you might need to rebase on latest main since there were some fixes to OnCluster tests, sorry for inconvenience.

**Comment by chzhyang** [comment]
> @chzhyang you might need to rebase on latest main since there were some fixes to OnCluster tests, sorry for inconvenience.

Thank you, I have rebased my PR, please review

**Review by zroubalik — APPROVED** [review]
/lgtm

**Pull request merged**
