### PR TITLE
fix: use default socket path for TCP connections

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :bug: Fix issues with TCP TLS connection.

resolves: #668

### CODE REVIEW

**Comment by matejvasek** [comment]
The `Func E2E Test / E2E Test (1.16.x, ubuntu-latest)` failure is probably flake.

**Comment by lance** [comment]
> The `Func E2E Test / E2E Test (1.16.x, ubuntu-latest)` failure is probably flake.

I re-ran the jobs - we'll see how it goes.

**Comment by matejvasek** [comment]
@lance  this needs rebase on the fix for node builders

**Review by lance — COMMENTED** [review]
/lgtm

**Pull request merged**
