### PR TITLE
feat: add flag to push image at the end of a successful build

### PR DESCRIPTION
**Pull request by shinigambit**
# Changes

- First approach for #676 

Currently have some debug statements in the code because I'm having an issue where the `push` flag is available to the command but it's not getting picked up by viper

### CODE REVIEW

**Comment by salaboy** [comment]
@shinigambit this is looking good.. what is going on with the e2e tests? It will be good not to change the default behaviour of build or even deploy with this change.

**Comment by salaboy** [comment]
@shinigambit let's ping @lance and @zroubalik .. can you guys confirm that these are real issues/failing tests? I am a bit afraid that this might be an issue with the platform more than actual issues with the code.

**Comment by salaboy** [comment]
I don't have enough rights to re-trigger the tests

**Comment by lance** [comment]
I tried re-running the integration tests and they failed again. I don't think this is a problem with the test environment. Have you tried running integration tests locally? `make test-integration`

**Comment by shinigambit** [comment]
I've found one integration test that fails but it doesn't happen all the time it's `TestNew` in `client_int_test.go` which I ran as follows
`go test -v -run ^TestNew$ client_int_test.go`
When it passes it shows the following message:
```
https://testnew/
Removing Knative Service: testnew
--- PASS: TestNew (17.52s)
PASS
```
When it fails it shows the following message:
```
Waiting for Knative Service to become ready
    client_int_test.go:91: knative deployer failed to wait for the Knative Service to become ready: RevisionFailed: Revision "testnew-00001" failed with message: Unable to fetch image "localhost:5000/func/testnew:latest": failed to resolve image to digest: Get "https://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused; Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused.
--- FAIL: TestNew (20.32s)
FAIL
```
I'm running this in an actual Ubuntu machine in GCP (not sure if this is relevant)
The success/fail ratio seems to be exactly 50/50 with a success happening right after a fail and vice-versa @lance @salaboy

**Comment by shinigambit** [comment]
Ok it seems that when the test fails it leaves the `testnew` service lingering after the test execution, somehow that makes the test pass the next time it's executed and on a successful execution the service gets deleted and the cycle repeats

**Comment by shinigambit** [comment]
My bad, had to pass the function arg as a pointer to fix it @lance @salaboy

**Review by lance — COMMENTED** [review]
/lgtm

But..
/hold for rebase

**Review by lance — APPROVED** [review]
/lgtm

Thanks for getting this done! :100:

**Comment by salaboy** [comment]
Hopefully, we can get merged soon.. so I can update the tekton tasks before I leave on holidays.

**Review by zroubalik — COMMENTED** [review]
/lgtm

**Comment by zroubalik** [comment]
@salaboy not sure if you are still around, but this is merged

**Pull request merged**
