### PR TITLE
fix: correct error handling in filesystem tests

### PR DESCRIPTION
**Pull request by menehune23**
Fixes a small typo in filesystem tests, so errors output correctly

### CODE REVIEW

**Comment by matejvasek** [comment]
@menehune23 Thanks for the contribution!

**Comment by matejvasek** [comment]
You will have to sign EasyCLA.

**Comment by menehune23** [comment]
Thanks @matejvasek. Working on the CLA part, though for some reason the CLA link is not loading for me. Does it repro for you? (https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/25619798/242137258/1226/#/?version=2)

**Pull request merged**
