### PR TITLE
feat: builder images map migration

### LINKED ISSUE #1022: func.yaml per-builder settings
The func.yaml currently specifies a `Builder` and `Builders` which are in need of update.

While it is possible the naming may change, to make it consistent with our current logic, the Builder setting would be removed, and the key of the `builders` map should be set to either `s2i` or `buildpack`, whose value is the builder image the named builder should use.  

Currently, the value of Builder, if it exists, is used as the builder image regardless of which builder type is chosen.  This of course has the unintended effect of "pinning" any function which uses this field to one builder type or another.

[Docs](https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/reference/func_yaml.md) should be uddpated, along with the schema, and It would be ideal if this came with a func.yaml Migration as well.

### PR DESCRIPTION
**Pull request by lkingland**
:gift: Function auto-migration to `builderImages` map

func.yaml now includes a `builderImages` map which allows Functions to specify builder-specific images to use when building.  This deprecates the non-specific `builder` and `builders` attiributes.  This PR migrates Functions which were created prior to this deprecation by either removing the attributes if unused, or carrying them over if the user had customized the value.  This (along with #1024 and #1028) Fixes #1022

/kind enhancement

### CODE REVIEW

**Comment by zroubalik** [comment]
@lkingland could you please rebase this PR so it includes only new changes? It's easier to do the review then

**Comment by lkingland** [comment]
> @lkingland could you please rebase this PR so it includes only new changes? It's easier to do the review then

Done; I should have done that before removing this from draft status.  Thanks for taking a look @zroubalik

**Review by zroubalik — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
