### PR TITLE
fix: use full image names

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes
Using full and non-docker.io names for `paketo` buildpack builders.
Useful when working with `podman` which dislike short names.

### CODE REVIEW

**Comment by matejvasek** [comment]
@jrangelramos I don't know what are implications with regard to pull limit in `gcr.io`.

**Comment by matejvasek** [comment]
This is not super important but it is more convenient for user because by default short names are forbidden in `podman`.

**Comment by jrangelramos** [comment]
@matejvasek so far I have not seen pull limit issue using gcr.io. Let see how it goes along the way. /lgtm

**Review by lance — APPROVED** [review]
/lgtm

**Pull request merged**
