### PR TITLE
fix: use domain qualified registry for springboot

### PR DESCRIPTION
**Pull request by lance**
:bug: The builder image name should include the registry name. Also it seems that the tiny builder doesn't actually work. We need base.

Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/775

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Comment by matejvasek** [comment]
@lance you might need to regenerate `pkged.go`

**Comment by matejvasek** [comment]
> @lance you might need to regenerate `pkged.go`

but maybe it's fault of CI and the `pkged.go` is alright.

**Comment by lance** [comment]
@matejvasek I think it's just because I'm using go 1.16 - confirmed. Regenerated with 1.17

**Pull request merged**
