### PR TITLE
docs: parameter `-P` is not needed in grep in pre-commit hook

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

### CODE REVIEW

**Comment by matejvasek** [comment]
@zroubalik I think you can remove the `P` directly from the script.

**Comment by zroubalik** [comment]
@matejvasek is it working for you as well? without the `-P`?

**Comment by matejvasek** [comment]
> @matejvasek is it working for you as well? without the `-P`?

I think it should.

**Comment by zroubalik** [comment]
@matejvasek fixed PTAL

**Pull request merged**
