### PR TITLE
Vendor dependencies

### PR DESCRIPTION
**Pull request by markusthoemmes**
# Changes

Shaking the tree.

As per title this introduces vendoring of the dependencies as a first step to transform the repo toward's Knative's dep-bump infra.

### CODE REVIEW

**Review by lkingland — APPROVED** [review]

**Comment by markusthoemmes** [comment]
I was having issues with the integration test, I'd like to see that pass first.

**Comment by markusthoemmes** [comment]
/unhold

This should be good now.

**Comment by lkingland** [comment]
Nice to see all those green checkmarks.
/lgtm

**Pull request merged**
