### PR TITLE
Windows unit test fixes

### PR DESCRIPTION
**Pull request by matejvasek**
* force unit test run by using `.PHONY` in `Makefile`
* fixed issues related to using back slash in path part of URI
* disabled few tests on Windows since I am not able to debug it

### CODE REVIEW

**Comment by matejvasek** [comment]
The unit test must have been broken for Windows for some time now.
For some reason the test were not run in CI,
the make command though the `test` recipe is satisfied (`mingw32-make: 'test' is up to date.`).

**Comment by matejvasek** [comment]
Even after few fixes this still fails. I have absolutely no idea why.
The Win tests pass all right on my machine: `fedora`+`wine`.

**Comment by matejvasek** [comment]
Could anybody with Windows machine try this?

**Comment by matejvasek** [comment]
@lkingland @lance PTAL

**Comment by lkingland** [comment]
With so many tests disabled in-code, I am leaning towards perhaps a different solution:

Could we just duisable Windows from the CI task entirely, and open a _new_ Issue for fixing Wndows the unit tests?  That would require merely [removing `windows-latest` from the CI task](https://github.com/knative-sandbox/kn-plugin-func/blob/main/.github/workflows/test-unit.yaml#L12), and be quite obvious what needs to be fixed via the issue.

Anyone else have an opinion?

**Comment by matejvasek** [comment]
@lkingland better to run some test than none. Right know there are only issues with custom git repositories.

**Comment by matejvasek** [comment]
Note: At first I suspected there is some issue with `file://` URLs on windows, but even when I switched to `http://` it didn't work.

**Comment by matejvasek** [comment]
@lkingland @lance PTAL I think we should merge this as it is.

**Comment by lkingland** [comment]
> @lkingland @lance PTAL I think we should merge this as it is.

That sounds good to me too.  We need to keep the momentum towards our upcoming release.  Let's just make sure we circle back to this when we have time.  These would be a great task to ask others with windows-specific experience to help debug.

/lgtm

**Review by lkingland — APPROVED** [review]

**Comment by matejvasek** [comment]
https://github.com/knative-sandbox/kn-plugin-func/issues/864

**Pull request merged**
