### PR TITLE
Improve template ZIP generation

### PR DESCRIPTION
**Pull request by matejvasek**
Use only 755 and 644 mod permission, not exact mod from local FS.
The exec bit is the only one that we really care about.

Also other bits may be set differently on developer machines depending
on its configuration, this would affect generation reproducibility.
For instance on some developer's machines, regular files have mod 664 rather that usual 644 for some reason.

### CODE REVIEW

**Comment by matejvasek** [comment]
@trisberg please try this on your macOS machine. Hopefuly is should produce identical `zz_filesystem_generated.go` file there.

**Comment by matejvasek** [comment]
AFAIK `git` also knows  755 and 644 only.

**Comment by trisberg** [comment]
I tried this on my Ubuntu system with umask set to 0002 and also 0022 - both runs worked fine now - no difference in the generated file.

**Review by lkingland — COMMENTED** [review]
This is a good change.  It should really help insulate against differences in developer machines permissions settings.

Would you mind adding an explanatory comment above, because this is a bit unobvious why it is required?

**Comment by matejvasek** [comment]
@lkingland @zroubalik @lance PTAL

**Pull request merged**
