### PR TITLE
On cluster build: support Build Envs

### LINKED ISSUE #1173: On-cluster build: Support Build Envs

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

# Changes

- :gift: On cluster build: support Build Envs

/kind enhancement

Fixes #1173

### CODE REVIEW

**Comment by jrangelramos** [comment]
Tested ok
/lgtm

**Comment by matejvasek** [comment]
Since when is `codecov/patch` required?

**Comment by jrangelramos** [comment]
@matejvasek it seems it is enabled by default. To disable it https://docs.codecov.com/docs/github-checks#yaml-configuration-for-github-checks-and-codecov

**Comment by matejvasek** [comment]
@jrangelramos I recall we were able to merge issues before with the test failing.

**Comment by matejvasek** [comment]
@zroubalik you might need to add some tests to pass checks.

**Comment by lance** [comment]
> @jrangelramos I recall we were able to merge issues before with the test failing.

I believe it was a 10% difference in code coverage that would trigger a failed status check - or at least one that prevented merge.

**Comment by zroubalik** [comment]
> > @jrangelramos I recall we were able to merge issues before with the test failing.
> 
> I believe it was a 10% difference in code coverage that would trigger a failed status check - or at least one that prevented merge.

Hmm, but codecov reports this:
`Merging #1174 (f269141) into main (3af2ea3) will decrease coverage by 0.13%.` 

Nowhere near 10% 😅

**Comment by zroubalik** [comment]
can I get LGTM again? Also I am not sure if there's a way to extend test coverage in this PR that would actually make sense.

**Comment by matejvasek** [comment]
/lgtm
but it won't help

**Pull request merged**
