### PR TITLE
feat: make SpringBoot template SpringNative by default

### LINKED ISSUE #630: Support func Spring Native template
Add a template for Spring Boot with Spring Native to leverage GraalVM runtimes.

### PR DESCRIPTION
**Pull request by salaboy**
# Changes

:broom:  update `springboot` templates to use SpringNative by default. Also, documents how to disable native build if it can't be used.

/kind cleanup

Fixes #630

This PR depends on this to be merged: https://github.com/knative-sandbox/kn-plugin-func/pull/646

### CODE REVIEW

**Comment by salaboy** [comment]
@lance @lkingland I think this requires a new lgtm

**Comment by lkingland** [comment]
So this is no longer a [WIP]?

**Comment by salaboy** [comment]
@lkingland WIP removed

**Comment by lance** [comment]
/unhold
/lgtm
/approve
push all the buttons! :laughing:

**Pull request merged**
