### PR TITLE
Adding ko to produce image with func command

### LINKED ISSUE #691: Create `func` container for automation
Having `func` bundled up as a container will help to use `func` into CI/CD automation pipelines, enabling integrations with tools like [Tekton](HTTP://tekton.dev)

### PR DESCRIPTION
**Pull request by salaboy**
# Changes
- :gift: Adding `ko` manifest to produce `func` container. 

You can produce a container by running:
```
ko publish ./cmd/func
```

Fixes #691

/kind enhancement

### CODE REVIEW

**Comment by salaboy** [comment]
@lance This will require to be hooked into some kind of automation. I am not sure to have enough context to do that.. I am happy to check that if you give me some pointers.

**Comment by lance** [comment]
> @lance This will require to be hooked into some kind of automation. I am not sure to have enough context to do that.. I am happy to check that if you give me some pointers.

What about adding a section to `.github/workflows/ci.yaml` to publish a snapshot with each commit to `main`? I will also need to consider this for release automation as well.

**Comment by lance** [comment]
@salaboy were you wanting to add some automation to this PR or follow up with another?

**Comment by zroubalik** [comment]
> @salaboy were you wanting to add some automation to this PR or follow up with another?

@lance I have fixed this in https://github.com/knative-sandbox/kn-plugin-func/pull/735

**Pull request merged**
