### PR TITLE
mitigate log4j dependency vulnerability

### LINKED ISSUE #722: Mitigate Log4j CVE in Springboot's default templates (http and cloudevents)

### PR DESCRIPTION
**Pull request by shinigambit**
Fixes #722

### CODE REVIEW

**Comment by matejvasek** [comment]
@shinigambit could we use 2.16?
otherwise lgtm

**Comment by matejvasek** [comment]
@shinigambit you also need to regenerate and commit `pkged.go`.

**Review by lance — COMMENTED** [review]
/lgtm after pkged.go is resolved

**Comment by matejvasek** [comment]
@shinigambit have you rebased on latest main?

**Comment by matejvasek** [comment]
Looks like you did rebase, maybe try regenerate pkged.go again?

**Comment by shinigambit** [comment]
> 

I tried that but it leaves `pkged.go` unchanged

**Comment by shinigambit** [comment]
@matejvasek the problem seems to be the `// +build !skippkger` annotation, should I fix it manually?

**Comment by matejvasek** [comment]
@shinigambit I not sure how to fix it, you shouldn't manually edit the file. What is your local version of `pkger`/`Go`?

**Comment by matejvasek** [comment]
@lkingland any idea what could be wrong?

**Comment by lance** [comment]
@matejvasek @shinigambit seems like everything is good now, isn't it?

**Comment by shinigambit** [comment]
@lance had to fix the tag in `pkged.go` but it's fine now, probably had to do with my go version, I see the verify step uses go 1.17 and I'm still on go 1.16.8 so that could be the reason

**Comment by lkingland** [comment]
> had to fix the tag in `pkged.go` but it's fine now, probably had to do with my go version

It's not you :)  This error appears to be because, as of Go1.17 [`//go:build` is preferred over the old `// +build` format](https://go.dev/doc/go1.17#build-lines), and all source _should_ be updated to include both.  The Our CI source format check action is enforcing this as a _must_.

Fortunately, there is a migration built into `gofmt`, so now rebuilding templates should ensure `pkged.go` is correct.  Sorry for the inconvenience!  Fix: #726

**Pull request merged**
