### PR TITLE
fix: performance of template loading

### PR DESCRIPTION
**Pull request by matejvasek**
# Changes

- :bug: Optimise template loading: use locally checked out files, i.e. do not re-clone content from `.git/` dir.

resolves: #1186

### CODE REVIEW

**Comment by matejvasek** [comment]
Please try this out @sudhirverma

**Comment by sudhirverma** [comment]
> Please try this out @sudhirverma this turns 40sec into 0.131sec.

Thanks, @matejvasek now it execute the command fast :)

**Review by zroubalik — APPROVED** [review]
/lgtm

/hold for others

**Review by lance — COMMENTED** [review]
/lgtm

**Pull request merged**
