### PR TITLE
feat: command help text template preprocessing

### LINKED ISSUE #216: Use `kn function` in help message when run as a plugin to kn
This requires two things:

* Set a flag when the `init()` method is called when the plugin registers itself
* Evaluate that flag when creating the root command. Unfortunately by standard Cobra mean it is not possible to set a two-level command name directly. Therefor we need to adjust the generation of the help messages, but we need to do this anyway because of #215

### PR DESCRIPTION
**Pull request by lkingland**
# Changes

- :gift: all command help text template preprocessed

In preparation for a complete update of all command help text, this PR updates all commands to have their help text passed through a template preprocessor which, by default, provides the effective command name.

/kind enhancement

Fixes #216

### CODE REVIEW

**Review by zroubalik — APPROVED** [review]
/lgtm

**Comment by zroubalik** [comment]
@lkingland there's a conflict to be resolved

**Comment by lkingland** [comment]
> @lkingland there's a conflict to be resolved

Thanks @zroubalik , logs of rebasing needed...

**Review by zroubalik — APPROVED** [review]
/lgtm

**Pull request merged**
