### PR TITLE
Enable custom CA for specified server names

### PR DESCRIPTION
**Pull request by matejvasek**
Allow usage of custom Certification Authority for specified host names.

### CODE REVIEW

**Comment by matejvasek** [comment]
@knative-sandbox/kn-plugin-func-approvers PTAL

**Comment by matejvasek** [comment]
This is needed for OpenShift internal registry push.

**Review by zroubalik — COMMENTED** [review]
/approve

**Comment by matejvasek** [comment]
@zroubalik can you lgtm?

**Review by zroubalik — APPROVED** [review]
/lgtm

**Pull request merged**
