### PR TITLE
doc: add documentation for using podman remotely

### PR DESCRIPTION
**Pull request by lance**
- 📖   This commit adds more documentation for using podman, specifically in this case, connecting to and using a remote podman service from a Mac computer.

/kind documentation

### CODE REVIEW

**Comment by matejvasek** [comment]
I find the name `registry` confusing there, it suggest relation to image registry in my mind.
Maybe rename it to `my-remote-machine`.

**Comment by lance** [comment]
> I find the name `registry` confusing there, it suggest relation to image registry in my mind. Maybe rename it to `my-remote-machine`.

@matejvasek I renamed to `podman-remote` - wdyt?

**Comment by matejvasek** [comment]
I think that's fine.

**Pull request merged**
