### PR TITLE
Fix a typo in Quarkus template README.md

### PR DESCRIPTION
**Pull request by aliok**
# Changes

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by matejvasek** [comment]
@aliok you need to re-generate embedded FS https://github.com/knative-sandbox/kn-plugin-func/actions/runs/3158654602/jobs/5140932625

**Review by lkingland — APPROVED** [review]

**Comment by lkingland** [comment]
Templates are embedded in the go source code as `zz_filesystem_generated.go`.    Therefore any update to a template, even a readme, requires that that file be regenerated.

I am pretty sure this is done automatically if you run `make`

**Comment by lkingland** [comment]
> # Changes
> 
> 
> /kind
> 
> Fixes #
> 
> **Release Note**
> 
> ```
> 
> ```
> 
> **Docs**
> 
> ```
> 
> ```

Might be nice to populate the PR content
```
- :broom: fix typo in quarkus template README.md

/kind cleanup
```

**Comment by matejvasek** [comment]
@aliok you need to also commit generated file: https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/CONTRIBUTING.md#templates

otherwise LGTM

**Pull request merged**
