### PR TITLE
chore: update springboot dependencies

### LINKED ISSUE #1061: Update Spring Boot Dependencies for Templates
- Update Spring Boot & Spring Cloud versions to:
  - Spring Boot 2.7.1
  - Spring Cloud Functions 2021.0.3
  - Spring Native 0.12.1

### PR DESCRIPTION
**Pull request by vyasgun**
# Changes
- Update Spring Boot & Spring Cloud versions to:
    - Spring Boot 2.7.1
    - Spring Cloud Functions 2021.0.3
    - Spring Native 0.12.1

/kind enhancement

Fixes #1061

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by matejvasek** [comment]
@vyasgun you need to regenerate the zz_* file.

**Comment by matejvasek** [comment]
@salaboy @shinigambit is there way to automate this like: https://github.com/knative-sandbox/kn-plugin-func/blob/main/hack/update-quarkus-platform.js ?

**Comment by salaboy** [comment]
@matejvasek I think we should do that automation.. let me create an issue for that

**Pull request merged**
