### PR TITLE
Update Go in actions to 1.18

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- Update Go in actions to 1.18

/cc @matejvasek @salaboy

### CODE REVIEW

**Comment by matejvasek** [comment]
@dsimansk what about `.github/workflows/knative-boilerplate.yaml` ?

**Comment by dsimansk** [comment]
> @dsimansk what about `.github/workflows/knative-boilerplate.yaml` ?

I didn't want to touch knative-* actions, because they're managed by auto-updates from knative automation.

**Review by salaboy — APPROVED** [review]

**Review by matejvasek — APPROVED** [review]

**Comment by matejvasek** [comment]
@dsimansk please rebase to fix the failing onCluster test.

**Pull request merged**
